// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwtmDPssmbYlbKOXzSxi8jk3MiZbKWA3w',
    appId: '1:373993258946:web:d734d0af545b2e094da05b',
    messagingSenderId: '373993258946',
    projectId: 'laari-app-owner-6c9d9',
    authDomain: 'laari-app-owner-6c9d9.firebaseapp.com',
    storageBucket: 'laari-app-owner-6c9d9.firebasestorage.app',
    measurementId: 'G-RLQMEHWDF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVUJUOjZH57NYkkb8EYfGJpodg02IrTVQ',
    appId: '1:373993258946:android:a56f680474c2d0594da05b',
    messagingSenderId: '373993258946',
    projectId: 'laari-app-owner-6c9d9',
    storageBucket: 'laari-app-owner-6c9d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZPyoV6ctvTOxW869MZnIRFib4NxMAMlU',
    appId: '1:373993258946:ios:e5265704bab72dc74da05b',
    messagingSenderId: '373993258946',
    projectId: 'laari-app-owner-6c9d9',
    storageBucket: 'laari-app-owner-6c9d9.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZPyoV6ctvTOxW869MZnIRFib4NxMAMlU',
    appId: '1:373993258946:ios:e5265704bab72dc74da05b',
    messagingSenderId: '373993258946',
    projectId: 'laari-app-owner-6c9d9',
    storageBucket: 'laari-app-owner-6c9d9.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwtmDPssmbYlbKOXzSxi8jk3MiZbKWA3w',
    appId: '1:373993258946:web:ca5df99f03bfac5e4da05b',
    messagingSenderId: '373993258946',
    projectId: 'laari-app-owner-6c9d9',
    authDomain: 'laari-app-owner-6c9d9.firebaseapp.com',
    storageBucket: 'laari-app-owner-6c9d9.firebasestorage.app',
    measurementId: 'G-5CZZQQSRMZ',
  );
}
